//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthKitTest.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuthKitTest.Api.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials.
        /// </summary>
        public static string AuthKit_Auth_InvalidCredentials {
            get {
                return ResourceManager.GetString("AuthKit.Auth.InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email or password provided is incorrect.
        /// </summary>
        public static string AuthKit_Auth_InvalidCredentialsDetails {
            get {
                return ResourceManager.GetString("AuthKit.Auth.InvalidCredentialsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission &apos;{0}&apos; is required to access this resource..
        /// </summary>
        public static string AuthKit_Auth_PermissionRequired {
            get {
                return ResourceManager.GetString("AuthKit.Auth.PermissionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This resource is only accessible from the &apos;{0}&apos; portal..
        /// </summary>
        public static string AuthKit_Auth_PortalAccessRestricted {
            get {
                return ResourceManager.GetString("AuthKit.Auth.PortalAccessRestricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal &apos;{0}&apos; is not configured..
        /// </summary>
        public static string AuthKit_Auth_PortalNotConfigured {
            get {
                return ResourceManager.GetString("AuthKit.Auth.PortalNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account does not have the required permissions to access this portal..
        /// </summary>
        public static string AuthKit_Auth_PortalPermissionNotAllowed {
            get {
                return ResourceManager.GetString("AuthKit.Auth.PortalPermissionNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account does not have the required role to access this portal..
        /// </summary>
        public static string AuthKit_Auth_PortalRoleNotAllowed {
            get {
                return ResourceManager.GetString("AuthKit.Auth.PortalRoleNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The refresh token has expired..
        /// </summary>
        public static string AuthKit_Auth_RefreshTokenExpired {
            get {
                return ResourceManager.GetString("AuthKit.Auth.RefreshTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The refresh token is invalid..
        /// </summary>
        public static string AuthKit_Auth_RefreshTokenInvalid {
            get {
                return ResourceManager.GetString("AuthKit.Auth.RefreshTokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The refresh token has been revoked..
        /// </summary>
        public static string AuthKit_Auth_RefreshTokenRevoked {
            get {
                return ResourceManager.GetString("AuthKit.Auth.RefreshTokenRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires all of the following roles: {0}..
        /// </summary>
        public static string AuthKit_Auth_RoleRequiredAll {
            get {
                return ResourceManager.GetString("AuthKit.Auth.RoleRequiredAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires one of the following roles: {0}..
        /// </summary>
        public static string AuthKit_Auth_RoleRequiredAny {
            get {
                return ResourceManager.GetString("AuthKit.Auth.RoleRequiredAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social login provider &apos;{0}&apos; is not supported..
        /// </summary>
        public static string AuthKit_Auth_SocialProviderNotSupported {
            get {
                return ResourceManager.GetString("AuthKit.Auth.SocialProviderNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hiii.
        /// </summary>
        public static string hello {
            get {
                return ResourceManager.GetString("hello", resourceCulture);
            }
        }
    }
}
